Masnet3/ViewComponents/ShareListViewComponent.cs
using MASNET.DataAccess;
using MASNET.DataAccess.Constants.Enums;
using Masnet3.Business.Repository;
using Masnet3.Common;
using Masnet3.Common.Utilities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Masnet3.ViewComponents
{
    public class ShareListViewComponent : ViewComponent
    {
        private readonly IRepositoryBasic repositoryBasic;
        public ShareListViewComponent(IRepositoryBasic repositoryBasic)
        {
            this.repositoryBasic = repositoryBasic;
        }
        public async Task<IViewComponentResult> InvokeAsync(Share model)
        {
            var site = GlobalVariables.SiteInformation;
            string customView = model.customView;
            string shareURL = model.shareURL;
            long contestantentryid = model.contestantentryid;
            long contestantID = model.contestantID;
            int returnFormat = model.returnFormat;
            bool bFlag = model.bFlag;
            bool isNotDeActivate = model.isNotDeActivate;
            int? contestID = model.ContestID;
            int? sourceID = model.sourceID;
            int mediaId = model.MediaId;
            string videoPath = model.VideoPath;
            string shareLinkType = model.ShareLinkType;
            string thumbnailUrl = model.ThumbnailUrl;
            string thumbnailDefaultUrl = model.ThumbnailDefaultUrl;
            List<int> actions = model.actions;

            if (sourceID == (int)Enums.PageID.HomePage && site.ApplicationID > 0)
                contestID = 0;

            var user = SessionUtilities.CurrentUser;
            var date = DateTime.Now.AddDays(1).ToString("yyyy-MM-dd");
            var lowerDate = DateTime.Now.ToString("yyyy-MM-dd");
            
            Period activeperiod = PeriodUilities.GetActivePeriod(site.ApplicationID, contestID);
            int ShareFrequency = Convert.ToInt32(Commons.Config["SharingFrequency"]);
            string sql = @"
                        SELECT ActionID FROM AccountDetail 
                        WHERE ContestID = @ContestID  AND [ShareStatus] = 1 ";
            sql += (SessionUtilities.IsLoggedIn() ? " AND UserID = @UserID " : " AND AnoUserID = @AnoUserID ");
            if (ShareFrequency == 1) // per Day
            {
                sql += " AND ContestantID = @ContestantID AND TransactionDate < @Date AND TransactionDate > @LowerDate ";
            }
            else if (ShareFrequency == 2) // per Promotion = from promotion start to end date
            {
                sql += "";
            }
            else if (ShareFrequency == 3) // per Hour
            {
                sql += " AND ContestantID = @ContestantID AND DATEDIFF (hour,TransactionDate,GETDATE()) = 0 ";
            }
            else if (ShareFrequency == 4)
            {   // Round
                sql += "";
            }
            else if (ShareFrequency == 5)
            { // Week
                sql += @" AND ContestantID = @ContestantID AND TransactionDate > DATEADD(DAY, 1 - DATEPART(WEEKDAY, GETDATE()), CAST(GETDATE() AS DATE))
                                      AND TransactionDate < DATEADD(DAY, 7 - DATEPART(WEEKDAY, GETDATE()) + 1, CAST(GETDATE() AS DATE))
                                ";
            }
            else if (ShareFrequency == 6)
            { // 5 mins
                sql += @" AND ContestantID = @ContestantID AND ABS(DATEDIFF (minute,TransactionDate,GETDATE())) < 5
                                ";
            }
            if (sourceID.HasValue && sourceID.Value > 0)
            {
                sql += " AND SourceID = @SourceID";
            }

            sql += " GROUP BY ActionID";
            var lsactions = await repositoryBasic.GetItemsDynamicSql_Task<int>(sql, new
            {
                PeriodID = activeperiod.PeriodID,
                Date = date,
                LowerDate = lowerDate,
                UserId = user.UserID,
                AnoUserID = CookieUtilities.GetCookie("id"),
                contestantentryid = contestantentryid,
                ContestantID = contestantID,
                ContestID = contestID.GetValueOrDefault(),
                SourceID = sourceID
            });
            actions = lsactions.ToList();

            var lstShare = ActionUitilites.GetActiveActions(Enums.SweepType.Period, activeperiod.PeriodID, site.ApplicationID, contestID);
            if (!string.IsNullOrEmpty(model.Exclude))
                lstShare = lstShare.Where(s => !model.Exclude.Split(',').Contains(s.ActionName));

            ViewBag.ActionID = actions;
            ViewBag.UseValidate = "1";
            ViewBag.ContestantentryID = contestantentryid;
            ViewBag.ContestantID = contestantID;
            ViewBag.shareURL = shareURL;
            ViewBag.isNotDeActivate = isNotDeActivate;
            ViewBag.sourceID = sourceID;
            ViewBag.contestID = contestID.GetValueOrDefault();
            ViewBag.MediaID = mediaId;
            ViewBag.VideoPath = videoPath;
            ViewBag.ShareLinkType = shareLinkType;
            ViewBag.ThumbnailUrl = thumbnailUrl;
            ViewBag.ThumbnailDefaultUrl = thumbnailDefaultUrl;

            model.actions = actions;
            ViewBag.Share = model;

            return View(customView, lstShare.ToList());
        }
    }
}

Masnet3/Views/Navigation/Header/_ContestFactory_Header.cshtml
@using Masnet3.Common.Helper;
@using Masnet3.Common.Utilities;
@using Masnet3.Common;
@using MASNET.DataAccess.Constants.Enums;
@using Masnet3.Business.Repository.Layout;
@model Masnet3.Model.ViewModel.LayoutViewModel
@{
    var urlLogo = string.Format("/Content/Themes/Default/images/", Model.SiteInformation.Theme.ThemeName) + "logo.png";
    if (!string.IsNullOrWhiteSpace(Model.SiteInformation.Logo))
    {
        urlLogo = Commons.ImageURL(Model.SiteInformation.Logo, "h");
    }

    if (SessionUtilities.IsLoggedIn() && Model.SiteInformation.SiteType == Enums.SiteType.Main)
    {
        return;
    }
    bool isForceLogin = (ViewContext.HttpContext.Request.Query["forcelogin"] + "").Equals("1");
}
<div class="col-sm-12">
    @*<div class="col-sm-1"></div>*@
    <div class="row-fluid">
        <a class="navbar-brand" href="@Url.SZAction("Index", "Home")">
            <img src="@urlLogo" style="max-height: 90px" />
        </a>
        <div class="pull-right">
            @Html.Partial("_Flags")
        </div>
    </div>
</div>
<div class="clearfix"></div>
@if (!isForceLogin)
{
    <div class="col-sm-12" style="background-color: #333;">
        @*<div class="col-sm-1"></div>*@
        <div class="row-fluid">
            <div class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0; ">
                <div class="navbar-header">
                    <button id="btnNavToggle" class="navbar-toggle collapsed" data-target="#divMainMenu" data-toggle="collapse" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <i class="icon icon-bars" style="font-size: 30px;"></i>
                    </button>
                </div>
                <div class="navbar-collapse collapse" style="width: 100%; height: 0px;" id="divMainMenu">
                    <ul class="nav navbar-nav" style="display: @(Model.SiteInformation.SiteStatus == Enums.SiteStatus.InvalidSite || Model.SiteInformation.SiteStatus == Enums.SiteStatus.Unpublished ? "none" : "")">

                        @if (!string.IsNullOrWhiteSpace(SessionUtilities.AdminUserToken))
                        {
                            <li class="divider-vertical"></li>
                            <li>
                                <a onclick="SwitchUser('@SessionUtilities.AdminUserToken'); return false;" style="cursor:pointer;">
                                    <i class="icon icon-gears"></i>
                                    @DbLanguage.GetText("gMenuAdminArea")
                                </a>
                            </li>
                        }
                    </ul>
                    <ul id="rightnav" class="nav navbar-nav navbar-right loginhandle">
                        @if (!SessionUtilities.IsLoggedIn())
                        {
                            if (Model.SiteInformation.SiteType == Enums.SiteType.Main && SessionUtilities.CurrentUser.UserID == 0 && false)
                            {
                                <li>
                                    <a href="@Url.SZAction("Register", "Customer", new { userType = (int)Enums.RegistrationUserType.Customer })">
                                        <i class="icon-user"></i>
                                        @DbLanguage.GetText("gRegisterUser")
                                    </a>
                                </li>
                            }
                            <li>
                                @if (Model.SiteInformation.SiteType == Enums.SiteType.Main)
                                {
                                    <button style="margin-right:10px;" onclick="window.location.href='@Url.SZAction("Register", "Customer", new { userType = (int)Enums.RegistrationUserType.Customer })'">@DbLanguage.GetText("gRegister")</button>
                                }
                                else
                                {
                                    <button style="margin-right:10px;" onclick="window.location.href='@Url.SZAction("Register", "Customer")'">@DbLanguage.GetText("gRegister")</button>
                                }
                                @if (Model.SiteInformation.SiteType == Enums.SiteType.Main && SessionUtilities.CurrentUser.UserID == 0 && false)
                                {
                                    <div style="text-align: center; width: 100px">
                                        <a href="@Url.SZAction("Register", "Customer", new { userType = (int)Enums.RegistrationUserType.Customer })">
                                            @DbLanguage.GetText("gRegisterUser")
                                        </a>
                                    </div>
                                }
                            </li>
                        }
                        else
                        {
                            <li>
                                <a href="@Url.SZAction("Edit", "MyAccount")">
                                    @{
                                        var avatar = GlobalVariables.DefaultAvatar;
                                        if (!string.IsNullOrWhiteSpace(SessionUtilities.CurrentUser.Photo))
                                        {
                                            avatar = Commons.ImageURL(SessionUtilities.CurrentUser.Photo, "s");
                                        }
                                    }
                                    <img id="CurrentUserPhoto_TopMenu" class="menu-user-photo img-circle" alt="@SessionUtilities.CurrentUser.Username" src="@avatar">
                                    <strong>@SessionUtilities.CurrentUser.Username</strong>
                                </a>
                            </li>
                        }
                        <li>
                            @{
                                string url = "", loginText = "";
                                if (SessionUtilities.IsLoggedIn())
                                {
                                    url = Url.SZAction("Logout", "Home");
                                    loginText = DbLanguage.GetText("gMenuLogout");
                                }
                                else
                                {
                                    if (!(Model.Controller.ToLower() == "home" && Model.Action.ToLower() == "customerlogin"))
                                    {
                                        url = Url.SZAction("CustomerLogin", "Home", new { returnUrl = ViewContext.HttpContext.Request.GetRawUrl() });
                                    }
                                    else
                                    {
                                        url = Url.SZAction("CustomerLogin", "Home");
                                    }
                                    loginText = DbLanguage.GetText("gMenuLogin");
                                }
                            }

                            @if (SessionUtilities.IsLoggedIn())
                            {
                                <a href="@url" class="button-logout">
                                    <i class="icon-power-off"></i>
                                    @loginText
                                </a>
                            }
                            else
                            {
                                <button style="margin-left: 0px" onclick="showLogonDialog();return false;">@loginText</button>
                            }
                        </li>
                        <li style="display: block; clear: both; width: 100%;">
                            <div id="login_dialog" @(Commons.Config["LoginStyle"] == "1" ? "class=logindropdown" : "") title="@DbLanguage.GetText("gLabel_Login")" style="display: none;"></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
}
<div class="clearer"></div>

Masnet3/Views/Navigation/Header/_Syngenta2018_soybean_Header.cshtml
@using Masnet3.Common.Helper;
@using Masnet3.Common.Utilities;
@using Masnet3.Common;
@using MASNET.DataAccess.Constants.Enums;
@model Masnet3.Model.ViewModel.LayoutViewModel

@if (Model.ShowLanguges && !SessionUtilities.IsUserHasAdminPermission() && !Model.Action.ToLower().Equals("customerlogin"))
{
    @Html.Partial("_Languages")
}

<div class="row row-header">
    <div class="col-sm-4 logo-container">
        <div class="logo-header">
            @if (SessionUtilities.IsUserHasAdminPermission() || Model.Action.ToLower().Equals("customerlogin"))
            {
                <img class="img-responsive" src="@Commons.ImageURL(Model.SiteInformation.Campaign.Photo, "")">
            }
            else
            {
                <a href="@Model.LogoUrl">
                    <img class="img-responsive" src="@Commons.ImageURL(Model.SiteInformation.Campaign.Photo, "")">
                </a>
            }

        </div>
    </div>
    <div class="col-sm-8 user-container">
        @if (Model.IsLogin)
        {
            if (Model.ExtraSetting != null)
            {
                if (Model.ExtraSetting["ShowLogin"] == 1)
                {
                    <ul class="list-inline">
                        <li class="welcome">
                            <div class="username">
                                @if (Model.IsSyngentaContext)
                                {
                                    <span class="fName">@Commons.Username(SessionUtilities.CurrentUser.FirstName, SessionUtilities.CurrentUser.LastName, SessionUtilities.CurrentUser.Username)</span>
                                }
                                else
                                {
                                    <span class="fName">@SessionUtilities.CurrentUser.FirstName</span>
                                    <span class="lName">@SessionUtilities.CurrentUser.LastName</span>
                                }
                            </div>
                            <a href="@Url.SZAction(" Logout", "Home" )">@DbLanguage.GetText("gMenuLogout")</a>
                        </li>
                    </ul>
                }
            }
            else
            {
                <ul class="list-inline">
                    <li class="welcome">
                        <div class="username">
                            @if (Model.IsSyngentaContext)
                            {
                                <span class="fName">@Commons.Username(SessionUtilities.CurrentUser.FirstName, SessionUtilities.CurrentUser.LastName, SessionUtilities.CurrentUser.Username)</span>
                            }
                            else
                            {
                                <span class="fName">@SessionUtilities.CurrentUser.FirstName</span>
                                <span class="lName">@SessionUtilities.CurrentUser.LastName</span>
                            }
                        </div>
                        <a href="@Url.SZAction(" Logout", "Home" )">@DbLanguage.GetText("gMenuLogout")</a>
                    </li>
                </ul>
            }

            if (!SessionUtilities.HasPermission(Enums.Permissions.Admin_Campaign_ReportViralDNA))
            {
                <ul class="list-inline">
                    @if (Model.IsNumberAnsweredQuestions == "1")
                    {
                        <li class="point numberAnswered">
                            <p>@DbLanguage.GetText("gAnswer", 1)</p>
                            <p><span id="numberAnswered">@Model.NumberAnswered</span></p>
                        </li>
                    }
                    @if (Model.IsNumberCorrectAnswered == "1")
                    {
                        <li class="point correctAnswered">
                            <p>@DbLanguage.GetText("gCorrectAnswers", 1)</p>
                            <p><span id="userCorrectAnswered">@Model.CorrectAnswered</span></p>
                        </li>
                    }
                    @if (Model.IsShowPoints == "1")
                    {
                        <li class="point">
                            <p>@DbLanguage.GetText("gAccountMenu_Points", 1)</p>
                            <p><span id="userPoint">@Model.Point</span></p>
                        </li>
                    }
                </ul>
            }
        }
        else
        {

            var site = GlobalVariables.SiteInformation;
            var SiteInformation = ViewBag.SiteInformation ?? GlobalVariables.SiteInformation;
            var pageShareURL = Url.Action("details", "contest", new { id = site.CampaignID }, RequestUtilities.Scheme());
            var conestId = SiteInformation.CampaignID;
            MASNET.DataAccess.Share modelShared = new MASNET.DataAccess.Share {
                customView = "_Sharing_Football",
                contestantentryid = 0,
                bFlag = true,
                contestantID = 0,
                shareURL = pageShareURL,
                isNotDeActivate = true,
                sourceID = (int)Enums.PageID.HomePage,
                ContestID = (int)conestId,
                Title = "Share this site",
                SourceType = (int)Enums.PageID.HomePage

            };
            @await Component.InvokeAsync("ShareList", new { model = modelShared });
        }
    </div>
</div>

<div id="logo-halex" class="logo-halex" style="display: none;">
    <img src="~/Content/themes/syngenta-soybean/images/hero.jpg" class="img-responsive" alt="" />
</div>

@if (Model.IsLogin && !Model.IsSyngentaContext)
{
    <nav role="navigation" id="NavLogined" class="navbar navbar-default navbar-custom" style="display: none;">
        <header>
            <!-- navigation -->
            <div id="header-navigation">
                <div class="container">
                    @if (!Model.IsPageContestended)
                    {
                        <!--/.nav-collapse -->
                        <div class="navbar-collapse collapse" id="divMainMenu">
                            @if (!SessionUtilities.HasPermission(Enums.Permissions.Admin_Campaign_ReportViralDNA))
                            {
                                <ul class="nav">
                                    @if (!Model.IsContestEnd)
                                    {
                                        <li class="@(Model.Action.ToLower() == " index" && Model.Controller.ToLower() == "quiz" ? "active" : "" )">
                                            <a href="@Url.Action(" Index", "Quiz" )">@DbLanguage.GetText("Menu_Trivia")</a>
                                        </li>
                                    }
                                    @if ((!Model.IsContestEnd || Model.IsSyngentaContext) && Model.IsShowLeaderBoard == "1")
                                    {
                                        <li class="@(Model.Action.ToLower() == " pointleader" && Model.Controller.ToLower() =="myaccount" ? "active" : "" )">
                                            <a href="@Url.Action(" PointLeader", "MyAccount" )">@DbLanguage.GetText("Title_PointLeader")</a>
                                        </li>
                                    }
                                    @if (!Model.IsContestEnd && Model.SpinAllow != "0")
                                    {
                                        <li class="" style="position:relative">
                                            <a href="javascript:void(0);" onclick="playSpin();">
                                                <i class="icon icon-bell bell" style="display:none;position:relative" aria-hidden="true">
                                                    <div class="spinnum" style="display:none">@Model.SpinCount</div>
                                                </i>
                                                <span id="spintab" class="disabledtab">
                                                    &nbsp;SpinZone<sup>&reg;</sup>
                                                </span>
                                            </a>
                                        </li>
                                    }
                                </ul>
                            }

                        </div>
                        <!--/.nav-collapse -->
                    }
                </div>
            </div>
            <!-- end navigation -->
        </header>
    </nav>
}

<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        var logoHalex = document.getElementById('logo-halex');
        var nav = document.getElementById('NavLogined');
        var parentNode = document.querySelector('.content-wrapper');
        var referenceNode = document.getElementById('divMainContainer');
        if (nav) {
            parentNode.insertBefore(nav, referenceNode);
            parentNode.insertBefore(logoHalex, nav);
            nav.style.display = 'block';
        } else {
            parentNode.insertBefore(logoHalex, referenceNode);
        }

        logoHalex.style.display = 'block';
    });
</script>

@if (Model.SiteInformation.IsPreview())
{
    <script src="~/Scripts/spinapi_upload.js"></script>
}